### ISSUE TITLE
Security Concerns

### ISSUE THREAD

**Issue by Ghvstcode** [DSC-UNIABUJA/p2p-tickets-api#1]
The Json web Tokens are showing in the development environment file! This is unsafe and is against the whole concept of using env variables

**Comment by solomon-os** [comment]
Really?

**Comment by Ghvstcode** [comment]
Yeah, standard practice is to not push your .env files as they can sometimes contain really important information like Passwords, so it's best to either make the repo private or even better don't push your environment variables, just set them when deploying!

**Comment by Eronmmer** [comment]
lol, it's clearly stated on the env file that it's for local development and testing purposes. we're obviously not using the same values in production

**Comment by Ghvstcode** [comment]
Alright then, But why go through all that stress of changing your Paystack key and JWT when you can just choose not to push it and add in the README that folks should generate theirs?
